environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm run build-ci

build: off

version: "{build}"

matrix:
  fast_finish: true